import 'package:flutter/material.dart';
import 'database.dart';
import 'models.dart';

void main()=>runApp(const CarDiagnosticApp());
class CarDiagnosticApp extends StatefulWidget{const CarDiagnosticApp({super.key});@override State<CarDiagnosticApp> createState()=>_CarDiagnosticAppState();}
class _CarDiagnosticAppState extends State<CarDiagnosticApp>{bool en=false;@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Car Diagnostic AI v4',theme:ThemeData(colorSchemeSeed:Colors.blue,useMaterial3:true),home:HomePage(en:en,onLanguage:()=>setState(()=>en=!en)));}
class HomePage extends StatefulWidget{final bool en;final VoidCallback onLanguage;const HomePage({super.key,required this.en,required this.onLanguage});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{final db=AppDatabase.instance;int page=0;bool loading=true;List<CarBrand> brands=[];List<CarModel> models=[];List<Generation> generations=[];List<Engine> engines=[];List<Category> categories=[];List<Subcategory> subs=[];List<DtcCode> dtcs=[];CarBrand? brand;CarModel? model;Generation? generation;Category? category;String q='';String t(String pl,String en)=>widget.en?en:pl;
@override void initState(){super.initState();_load();}
Future<void> _load() async{setState(()=>loading=true);await db.seedDatabase();final b=await db.getBrands();final c=await db.getCategories();final d=await db.getDtcCodes(query:q);if(!mounted)return;setState((){brands=b;categories=c;dtcs=d;loading=false;});}
Future<void> _selectBrand(CarBrand? x)async{if(x==null)return;final r=await db.getModels(x.id!);if(!mounted)return;setState((){brand=x;models=r;model=null;generations=[];generation=null;engines=[];});}
Future<void> _selectModel(CarModel? x)async{if(x==null)return;final r=await db.getGenerations(x.id!);if(!mounted)return;setState((){model=x;generations=r;generation=null;engines=[];});}
Future<void> _selectGeneration(Generation? x)async{if(x==null)return;final r=await db.getEngines(x.id!);if(!mounted)return;setState((){generation=x;engines=r;});}
Future<void> _selectCategory(Category? x)async{if(x==null)return;final r=await db.getSubcategories(x.id!);if(!mounted)return;setState((){category=x;subs=r;});}
void msg(String s){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
Future<void> confirmDelete(String table,int id,String label)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(t('Usunąć?','Delete?')),content:Text('$label\n${t('Element i jego zależne dane zostaną usunięte.','The item and dependent data will be deleted.')}'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:Text(t('Anuluj','Cancel'))),FilledButton(onPressed:()=>Navigator.pop(c,true),child:Text(t('Usuń','Delete')))]));if(ok!=true)return;await db.remove(table,id);if(!mounted)return;await _load();if(!mounted)return;setState((){brand=null;model=null;generation=null;models=[];generations=[];engines=[];category=null;subs=[];});msg(t('Usunięto','Deleted'));}
Future<void> dialog({required String title,required List<_Field> fields,required Future<void> Function(Map<String,String>) save})async{final cs={for(final f in fields)f.key:TextEditingController(text:f.value)};await showDialog(context:context,builder:(c)=>AlertDialog(title:Text(title),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:fields.map((f)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:cs[f.key],keyboardType:f.number?TextInputType.number:null,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder())))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(t('Anuluj','Cancel'))),FilledButton(onPressed:()async{final v={for(final e in cs.entries)e.key:e.value.text.trim()};await save(v);if(!c.mounted)return;Navigator.pop(c);},child:Text(t('Zapisz','Save')))]));}
Future<void> addEditBrand([CarBrand? x])=>dialog(title:x==null?t('Dodaj markę','Add brand'):t('Edytuj markę','Edit brand'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??'')],save:(v)async{if(v['name']!.isEmpty)return;if(x==null)await db.insert('brands',{'name':v['name']});else await db.update('brands',x.id!,{'name':v['name']});await _load();});
Future<void> addEditModel([CarModel? x])async{if(x==null&&brand==null){msg(t('Najpierw wybierz markę','Select a brand first'));return;}await dialog(title:t('Model','Model'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??'')],save:(v)async{if(v['name']!.isEmpty)return;if(x==null)await db.insert('models',{'brand_id':brand!.id,'name':v['name']});else await db.update('models',x.id!,{'name':v['name']});if(brand!=null)await _selectBrand(brand);});}
Future<void> addEditGeneration([Generation? x])async{if(x==null&&model==null){msg(t('Najpierw wybierz model','Select a model first'));return;}await dialog(title:t('Generacja','Generation'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??''),_Field('from',t('Rok od (opcjonalnie)','Year from (optional)'),x?.yearFrom?.toString()??'',true),_Field('to',t('Rok do (opcjonalnie)','Year to (optional)'),x?.yearTo?.toString()??'',true)],save:(v)async{if(v['name']!.isEmpty)return;final data={'name':v['name'],'year_from':int.tryParse(v['from']!), 'year_to':int.tryParse(v['to']!)};if(x==null){data['model_id']=model!.id;await db.insert('generations',data);}else await db.update('generations',x.id!,data);if(model!=null)await _selectModel(model);});}
Future<void> addEditEngine([Engine? x])async{if(x==null&&generation==null){msg(t('Najpierw wybierz generację','Select a generation first'));return;}await dialog(title:t('Silnik','Engine'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??''),_Field('code',t('Kod (opcjonalnie)','Code (optional)'),x?.code??''),_Field('fuel',t('Paliwo (opcjonalnie)','Fuel (optional)'),x?.fuel??''),_Field('cc',t('Pojemność (opcjonalnie)','Displacement (optional)'),x?.displacement?.toString()??'',true),_Field('power',t('Moc KM (opcjonalnie)','Power HP (optional)'),x?.power?.toString()??'',true)],save:(v)async{if(v['name']!.isEmpty)return;final data={'name':v['name'],'code':_null(v['code']!), 'fuel':_null(v['fuel']!), 'displacement':int.tryParse(v['cc']!), 'power':int.tryParse(v['power']!)};if(x==null){data['generation_id']=generation!.id;await db.insert('engines',data);}else await db.update('engines',x.id!,data);if(generation!=null)await _selectGeneration(generation);});}
String? _null(String x)=>x.isEmpty?null:x;
Future<void> addEditCategory([Category? x])=>dialog(title:t('Kategoria','Category'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??'')],save:(v)async{if(v['name']!.isEmpty)return;if(x==null)await db.insert('categories',{'name':v['name']});else await db.update('categories',x.id!,{'name':v['name']});await _load();});
Future<void> addEditSub([Subcategory? x])async{if(x==null&&category==null){msg(t('Najpierw wybierz kategorię','Select a category first'));return;}await dialog(title:t('Podkategoria','Subcategory'),fields:[_Field('name',t('Nazwa *','Name *'),x?.name??'')],save:(v)async{if(v['name']!.isEmpty)return;if(x==null)await db.insert('subcategories',{'category_id':category!.id,'name':v['name']});else await db.update('subcategories',x.id!,{'name':v['name']});if(category!=null)await _selectCategory(category);});}
Future<void> addEditDtc([DtcCode? x])async=>dialog(title:x==null?t('Dodaj błąd DTC','Add DTC'):t('Edytuj DTC','Edit DTC'),fields:[_Field('code',t('Kod *','Code *'),x?.code??''),_Field('desc',t('Opis domyślny *','Default description *'),x?.description??''),_Field('pl',t('Opis po polsku (opcjonalnie)','Polish description (optional)'),x?.descriptionPl??''),_Field('en',t('Opis po angielsku (opcjonalnie)','English description (optional)'),x?.descriptionEn??''),_Field('causes',t('Przyczyny (opcjonalnie)','Causes (optional)'),x?.causes??''),_Field('checks',t('Sprawdzenie (opcjonalnie)','Checks (optional)'),x?.checks??'')],save:(v)async{if(v['code']!.isEmpty||v['desc']!.isEmpty)return;final data={'code':v['code'],'description':v['desc'],'description_pl':_null(v['pl']!),'description_en':_null(v['en']!),'causes':_null(v['causes']!), 'checks':_null(v['checks']!)};if(x==null)await db.insert('dtc_codes',data);else await db.update('dtc_codes',x.id!,data);await _load();});
@override Widget build(BuildContext c){final titles=[t('Pojazdy','Vehicles'),t('Kategorie','Categories'),t('Błędy DTC','DTC codes')];return Scaffold(appBar:AppBar(title:Text('Car Diagnostic AI v4 — ${titles[page]}'),actions:[IconButton(onPressed:widget.onLanguage,icon:const Icon(Icons.language),tooltip:widget.en?'Polski':'English')]),body:loading?const Center(child:CircularProgressIndicator()):IndexedStack(index:page,children:[vehicles(),cats(),dtc()]),bottomNavigationBar:NavigationBar(selectedIndex:page,onDestinationSelected:(x)=>setState(()=>page=x),destinations:[NavigationDestination(icon:const Icon(Icons.directions_car),label:titles[0]),NavigationDestination(icon:const Icon(Icons.category),label:titles[1]),NavigationDestination(icon:const Icon(Icons.build),label:titles[2])]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>page==0?addEditBrand():page==1?addEditCategory():addEditDtc(),icon:const Icon(Icons.add),label:Text(t('Dodaj','Add'))));}
Widget section(String title,Widget child,VoidCallback add)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:Theme.of(context).textTheme.titleMedium)),IconButton(onPressed:add,icon:const Icon(Icons.add_circle_outline))]),child])));
Widget item(String text,VoidCallback tap,VoidCallback edit,VoidCallback del)=>ListTile(title:Text(text),onTap:tap,trailing:Wrap(children:[IconButton(onPressed:edit,icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:del,icon:const Icon(Icons.delete_outline))]));
Widget vehicles()=>ListView(padding:const EdgeInsets.all(12),children:[section(t('Marki','Brands'),Column(children:brands.map((x)=>item(x.name,()=>_selectBrand(x),()=>addEditBrand(x),()=>confirmDelete('brands',x.id!,x.name))).toList()),addEditBrand),if(brand!=null)section('${t('Modele','Models')} — ${brand!.name}',Column(children:models.map((x)=>item(x.name,()=>_selectModel(x),()=>addEditModel(x),()=>confirmDelete('models',x.id!,x.name))).toList()),addEditModel),if(model!=null)section('${t('Generacje','Generations')} — ${model!.name}',Column(children:generations.map((x)=>item('${x.name}${x.yearFrom!=null?' (${x.yearFrom}-${x.yearTo??''})':''}',()=>_selectGeneration(x),()=>addEditGeneration(x),()=>confirmDelete('generations',x.id!,x.name))).toList()),addEditGeneration),if(generation!=null)section('${t('Silniki','Engines')} — ${generation!.name}',Column(children:engines.map((x)=>item('${x.name}${x.code==null?'':' — ${x.code}'}',(){},()=>addEditEngine(x),()=>confirmDelete('engines',x.id!,x.name))).toList()),addEditEngine)]);
Widget cats()=>ListView(padding:const EdgeInsets.all(12),children:[section(t('Kategorie','Categories'),Column(children:categories.map((x)=>item(x.name,()=>_selectCategory(x),()=>addEditCategory(x),()=>confirmDelete('categories',x.id!,x.name))).toList()),addEditCategory),if(category!=null)section('${t('Podkategorie','Subcategories')} — ${category!.name}',Column(children:subs.map((x)=>item(x.name,(){},()=>addEditSub(x),()=>confirmDelete('subcategories',x.id!,x.name))).toList()),addEditSub)]);
Widget dtc()=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(onChanged:(x)async{q=x;final r=await db.getDtcCodes(query:q);if(!mounted)return;setState(()=>dtcs=r);},decoration:InputDecoration(prefixIcon:const Icon(Icons.search),labelText:t('Szukaj kodu lub opisu','Search code or description'),border:const OutlineInputBorder()))),Expanded(child:ListView.builder(itemCount:dtcs.length,itemBuilder:(c,i){final x=dtcs[i];final desc=widget.en?(x.descriptionEn??x.description):(x.descriptionPl??x.description);return Card(child:ListTile(title:Text('${x.code} — $desc'),subtitle:Text([x.causes,x.checks].whereType<String>().where((e)=>e.isNotEmpty).join('\n')),trailing:Wrap(children:[IconButton(onPressed:()=>addEditDtc(x),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>confirmDelete('dtc_codes',x.id!,x.code),icon:const Icon(Icons.delete_outline))]));}))]);}
}
class _Field{final String key,label,value;final bool number;const _Field(this.key,this.label,this.value,[this.number=false]);}
